[package]
name = "mosec"
version = "0.1.0"
authors = ["Keming <kemingy94@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
tokio = { version="1", features=["full"] }
derive_more = { version="0.99.0", features=["display", "error"] }
