name: PyPI Publish 🥳

on:
  release:
    types: [created]

jobs:
  publish:
    name: "Publish PyPI Package"
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2
      - name: Install latest stable rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Prepare conda environment
        run: bash ./scripts/prepare.sh
      - name: Build
        run: bash ./scripts/build.sh
      - name: Publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          python setup.py sdist
          twine upload dist/*
